### ISSUE TITLE
Godot scene `.tscn` icons do not render correctly on Latte theme

### ISSUE THREAD

**Issue by benediktms** [catppuccin/vscode-icons#175] opened 2024-06-05 16:51 UTC
### VSCode/Codium version

VSCode 1.89.1

### Extension version

1.13.0

### Describe the bug

As raised on https://github.com/catppuccin/vscode/issues/398 there seems to be an issue with the Latter versions of the Godot scene icons.
![Screenshot 2024-06-05 at 17 48 53](https://github.com/catppuccin/vscode-icons/assets/48836135/85f20e63-523f-43aa-8a28-341975028e5a)
The dark versions seem to work fine:
![Screenshot 2024-06-05 at 17 49 54](https://github.com/catppuccin/vscode-icons/assets/48836135/2164a1a4-0f76-489d-b86d-fd554ec26e6b)

I've tried completely uninstalling the extension and re-installing, but the result is the same. So far this is also the only icon that I get this behaviour with that I could find

**Comment by sgoudham** [comment] 2024-08-12 20:55
Hey there :wave:, 

I'm running VSCode v1.92.0 with the Catppuccin Icons extension v1.14.0. I'm not able to reproduce this error as shown in the screenshot below:

![image](https://github.com/user-attachments/assets/5a6a8cb4-8c2c-44e1-8d61-6116f2c22528)

Could you please try updating the extension / VSCode versions and see if that fixes it for you? I'll be closing this issue as I assume it's resolved but please feel free to re-open if you're still running this issue.

Thanks!

**Closed by sgoudham** 2024-08-12 20:55 UTC
Labels: bug
